---
title: "Lecture 6"
description: |
  TODO
draft: true
author:
  - name: Jannik Buhr 
    url: https://jmbuhr.de
date: 11-02-2020
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - lecture
bibliography: ["../../references.bib"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE
)
library(tidyverse)
```

# Video

Watch today's video here:

<iframe width="560" height="315" src="https://www.youtube.com/embed/AgpWX18dby4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

Hover over the slides and press **f** for full screen.
Press **?** for a list of keyboard shortcuts.

```{r}
knitr::include_url("slides2.html")
```

# Script


The Galton Board

```{r}
n_layers <- 15
p <- 0.5
n_paths <- 1000

get_random_path <- function(n_layers, p) {
  s <- sample(c(-0.5, 0.5), n_layers, replace = TRUE, prob = c(p, 1 - p))
  c(0, cumsum(s))
}

galton <- tibble(
  trial = 1:n_paths,
  path = map(trial, ~ get_random_path(n_layers, p))
) %>% 
  unnest_longer(path) %>% 
  group_by(trial) %>% 
  mutate(h = n():1)

board <- tibble(
  h = 1:n_layers,
  trial = 1
) %>% 
  mutate(path = map(h, function(h) {
    x <- (n_layers - h)
    (-x/2):(x/2)
  })) %>% 
  unnest_longer(path) %>% 
  mutate(h = h + 0.4)
```

```{r}
library(gganimate)

galton %>% 
  ggplot(aes(path, h, group = trial)) +
  geom_path(alpha = 0.1, size = 2,  lineend = "round") +
  geom_point(data = board) +
  theme_void() +
  # transition_reveal(along = trial) +
  NULL
```

```{r}
galton %>% 
  filter(h == 1) %>% 
  ggplot(aes(path)) +
  geom_histogram(aes(y = stat(count) / sum(count)), binwidth = 0.5)
```

## Visualising Distributions

## Summary Statistics









## Dimensionality reduction: PCA

Principle Component Analysis

```{r, warning=FALSE, message=FALSE}
songs <- read_csv("data/spotify_playlist.csv")
```


```{r}
plt <- songs %>% 
  ggplot(aes(x = energy,
             y = loudness,
             label = track_name)) +
  geom_point()

plotly::ggplotly(plt)
```






```{r}
plt <- songs %>% 
  ggplot(aes(track_year, track_popularity)) +
  geom_point()
plt
```

```{r}

```


```{r}
library(tidymodels)

songs_rec <- recipe(track_popularity ~ ., data = songs) %>% 
  update_role(track_name, track_artists,
              new_role = "id") %>% 
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())
```

```{r}
songs_prep <- prep(songs_rec)
tidy(songs_prep)
```

```{r}
songs_pca <- tidy(songs_prep, 2)
songs_pca %>% 
  filter(component %in% paste0("PC", 1:3)) %>% 
  ggplot(aes(value, terms, fill = value < 0)) +
  geom_col() +
  facet_wrap(vars(component))
```


```{r}
songs_juice <- juice(songs_prep)
songs_juice
```

```{r}
plt <- songs_juice %>% 
  mutate(song = paste(track_name, ",", track_artists)) %>% 
  ggplot(aes(PC1, PC2, label = song)) +
  geom_point()
plt
```

```{r}
plotly::ggplotly(plt)
```


```{r}
sdev <- songs_prep$steps[[2]]$res$sdev
percent_variation <- sdev^2 / sum(sdev^2)

tibble(
  component = unique(songs_pca$component),
  percent_var = percent_variation 
) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(component, percent_var)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(x = NULL, y = "Percent variance explained by each PCA component")
```


# Exercises

# Solutions

# Resources
