---
title: "Lecture 3"
description: |
  TODO
draft: true
author:
  - name: Jannik Buhr 
    url: https://jmbuhr.de
date: 11-02-2020
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - lecture
bibliography: ["../../references.bib"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

# Video

Watch today's video here:

<iframe width="560" height="315" src="https://www.youtube.com/embed/AgpWX18dby4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

Hover over the slides and press **f** for full screen.
Press **?** for a list of keyboard shortcuts.

```{r}
knitr::include_url("slides2.html")
```

# Script

## Iteration

### Reading in Multiple Files

```{r}
library(tidyverse)

read_csv("data/Africa.csv")

paths <- dir("data", full.names = TRUE)
names(paths) <- basename(paths) %>% str_remove("\\.csv")

my_data <- map(paths, read_csv)

combinded_data <- my_data %>% 
  bind_rows(.id = "continent")
```


```{r}
gapminder <- map_dfr(paths, read_csv, .id = "continent")
```


```{r}
results <- vector("list", length(paths))
for (i in 1:length(paths)) {
  data <- read_csv(paths[i])
  data$continent <- names(paths[1])
  results[[i]] <- data
}

dataset <- bind_rows(results)
dataset
```


# Exercises

# Solutions

# Resources
